from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from ai_core.config.loader import ConfigLoader
from ai_core.config.paths import CONFIGS_DIR, RUNTIME_GENERATED
from ai_core.events.event_bus import event_bus
from ai_core.runtime.bootstrap.model_requirement_generator import ModelRequirementGenerator
from ai_core.runtime.bootstrap.provider_discovery import ProviderDiscovery
from ai_core.runtime.governance.runtime_governance import RuntimeGovernanceRegistry


class RuntimeBootstrapService:
    """Initializes runtime cognitive topology at process startup.

    The runtime first tries to let a strong configured model generate a topology
    from current feature/provider inventories. If unavailable, it writes a seed
    topology so execution can continue deterministically.
    """

    OUTPUT_DIR = RUNTIME_GENERATED / "system_topology"
    OUTPUT_PATH = OUTPUT_DIR / "runtime_governance_graph.json"

    def __init__(self) -> None:
        self.loader = ConfigLoader()
        self.discovery = ProviderDiscovery()
        self.generator = ModelRequirementGenerator()
        self.governance = RuntimeGovernanceRegistry()

    async def bootstrap(self, *, force: bool = False) -> dict[str, Any]:
        """Bootstrap runtime topology without blocking API startup.

        Fast boot is the default. It must not call an LLM, pull a model, start a
        local model server, or do any heavy provider validation. The runtime can
        still be regenerated by a model later, but only when explicitly enabled
        with AI_CORE_BOOTSTRAP_USE_MODEL=1 and force=True.
        """
        if self.OUTPUT_PATH.exists() and not force:
            try:
                loaded = json.loads(self.OUTPUT_PATH.read_text(encoding="utf-8"))
                if isinstance(loaded, dict):
                    loaded.setdefault("fast_boot", True)
                    return loaded
            except Exception:
                pass

        run_id = "runtime_bootstrap_" + uuid4().hex[:10]
        feature_inventory = self.loader.load_json(CONFIGS_DIR / "runtime_feature_inventory.json")
        provider_inventory = self.discovery.discover()
        seed_topology = self.loader.load_json(CONFIGS_DIR / "runtime_bootstrap_seed_topology.json")
        await event_bus.emit(run_id, {
            "type": "RUNTIME_BOOTSTRAP_START",
            "title": "Runtime bootstrap started",
            "message": "Loading seed topology using fast boot.",
        })

        use_model = (
            force
            and os.environ.get("AI_CORE_BOOTSTRAP_USE_MODEL", "").strip().lower()
            in {"1", "true", "yes", "on"}
        )
        generated: dict[str, Any]
        source = "seed_fast_boot"
        if use_model:
            try:
                generated = await self.generator.generate(
                    run_id=run_id,
                    feature_inventory=feature_inventory,
                    provider_inventory=provider_inventory,
                    seed_topology=seed_topology,
                )
                source = "strong_model"
            except Exception as exc:
                generated = dict(seed_topology)
                generated["bootstrap_warning"] = str(exc)
                source = "seed_fallback"
        else:
            generated = dict(seed_topology)
            generated["bootstrap_note"] = (
                "Fast boot used seed topology. No LLM/provider/model startup was performed."
            )

        generated.setdefault("version", "2.8.16-fastboot")
        generated["bootstrap_source"] = source
        generated["fast_boot"] = not use_model
        generated["bootstrapped_at"] = datetime.now(timezone.utc).isoformat()
        generated["provider_inventory_snapshot"] = provider_inventory
        self.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        self.OUTPUT_PATH.write_text(json.dumps(generated, ensure_ascii=False, indent=2), encoding="utf-8")
        self.governance.write_bootstrap_artifacts(
            topology=generated,
            provider_inventory=provider_inventory,
            feature_inventory=feature_inventory,
            source=source,
        )
        await event_bus.emit(run_id, {
            "type": "RUNTIME_BOOTSTRAP_DONE",
            "title": "Runtime bootstrap completed",
            "message": "Topology source=" + source,
        })
        return generated
