from pathlib import Path
p=Path('/mnt/data/codework/ai_core/context/llm_stage_input_slimmer.py')
s=p.read_text()
s=s.replace('''    DEFAULT_TEXT_LIMITS = {\n        "agent_parameter_contract": 700,\n        "input_parsing": 650,\n        "intent_recognition": 700,\n        "workflow_planning": 800,\n        "execution": 700,\n    }''','''    DEFAULT_TEXT_LIMITS = {\n        "agent_parameter_contract": 520,\n        "input_parsing": 420,\n        "intent_recognition": 460,\n        "workflow_planning": 520,\n        "execution": 420,\n    }''')
s=s.replace('''    KEEP_INPUT_KEYS = {\n        "request",\n        "message",\n        "instruction",\n        "task_instruction",\n        "objective",\n        "expected_output",\n        "constraints",\n        "context",\n        "task_name",\n        "request_type",\n        "participant_name",\n        "runtime_parameters",\n        "agent_parameters",\n    }''','''    KEEP_INPUT_KEYS = {\n        "request",\n        "message",\n        "instruction",\n        "objective",\n        "constraints",\n        "context",\n        "participant_name",\n        "runtime_parameters",\n        "agent_parameters",\n    }''')
s=s.replace('''        for key in ("request_type", "task_name", "participant_name", "objective"):\n            value = payload.get(key)\n            if isinstance(value, (str, int, float, bool)) and str(value).strip():\n                compact[key] = value''','''        for key in ("participant_name", "objective"):\n            value = payload.get(key)\n            if isinstance(value, (str, int, float, bool)) and str(value).strip():\n                compact[key] = value''')
s=s.replace('''                "request_type": payload.get("request_type"),\n                "task_name": payload.get("task_name"),\n                "participant_name": payload.get("participant_name"),\n                "objective": payload.get("objective"),\n                "parameters": values,''','''                "participant_name": payload.get("participant_name"),\n                "objective": payload.get("objective"),\n                "parameters": values,''')
p.write_text(s)

p=Path('/mnt/data/codework/ai_core/agent_delegation/primary_brain_client.py')
s=p.read_text()
old='''    def _build_agent_message(self, request: AgentExecutionRequest) -> str:\n        import json\n\n        envelope = PrimaryRuntimeRequestEnvelope(\n            request_type="agent_execution",\n            task_name=request.task_name,\n            participant_name=request.participant_name,\n            participant_id=request.participant_id,\n            objective=(request.participant_instruction or "").strip(),\n            task_instruction=request.task_instruction,\n            community_id=request.community_id,\n            context=request.shared_context or {},\n            execution_policy=PrimaryRuntimeExecutionPolicy(),\n        )\n        return (\n            "Execute one participant request. Own objective is primary. "\n            "Peer results in context are supporting material only; use them only when they are relevant. "\n            "Do not redefine participants or tasks. Return only the participant final answer.\\n"\n            "JSON_ENVELOPE:\\n"\n            + json.dumps(envelope.to_prompt_payload(), ensure_ascii=False, separators=(",", ":"))\n        )\n'''
new='''    def _build_agent_message(self, request: AgentExecutionRequest) -> str:\n        import json\n\n        # Agent execution must be local to the participant.  Task-level routing\n        # data, graph metadata, and policy envelopes belong to the auxiliary\n        # coordinator and final synthesis, not to each participant LLM stage.\n        # Keeping this payload small prevents local JSON models from copying\n        # unrelated task text into workflow or execution prompts.\n        context = request.shared_context or {}\n        local_context = {}\n        if isinstance(context, dict):\n            for key in ("relationship", "depends_on", "agent_parameters", "available_peer_results"):\n                value = context.get(key)\n                if value not in (None, "", [], {}):\n                    local_context[key] = value\n        payload = {\n            "participant_name": request.participant_name,\n            "objective": (request.participant_instruction or "").strip(),\n        }\n        if local_context:\n            payload["context"] = local_context\n        return "AGENT_REQUEST=" + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))\n'''
if old not in s:
    raise SystemExit('old _build_agent_message not found')
s=s.replace(old,new)
p.write_text(s)

p=Path('/mnt/data/codework/ai_core/runtime/bootstrap/core_bootstrap.py')
s=p.read_text()
s=s.replace('''                "version": "2.3-micro",''','''                "version": "2.4-agent-local",''',1)
s=s.replace('''                "user_template": (\n                    "INPUT={{ user_input }}\\n"\n                    "TIME={{ runtime_context }}"\n                ),''','''                "user_template": (\n                    "AGENT={{ user_input }}\\n"\n                    "TIME={{ runtime_context }}"\n                ),''',1)
s=s.replace('''                "version": "2.3-micro",''','''                "version": "2.4-agent-local",''',1)
s=s.replace('''                "user_template": (\n                    "INPUT={{ user_input }}\\n"\n                    "PARSED={{ previous_results }}"\n                ),''','''                "user_template": (\n                    "AGENT={{ user_input }}\\n"\n                    "PARSED={{ previous_results }}"\n                ),''',1)
s=s.replace('''                "version": "2.3-micro",''','''                "version": "2.4-agent-local",''',1)
s=s.replace('''                "user_template": (\n                    "GOAL={{ user_input }}\\n"\n                    "STATE={{ previous_results }}"\n                ),''','''                "user_template": (\n                    "AGENT={{ user_input }}\\n"\n                    "STATE={{ previous_results }}"\n                ),''',1)
s=s.replace('''                    "Do not copy original_input or raw JSON envelopes.",''','''                    "Do not copy original_input, task instructions, or raw JSON envelopes.",''')
p.write_text(s)

# Add clean architecture note.
Path('/mnt/data/codework/CLEAN_RUNTIME_NOTES.md').write_text('''# Clean Runtime Notes\n\nThis package keeps task coordination data out of participant execution prompts.\n\n## Agent-local prompt contract\nEach participant receives only:\n\n```json\n{\n  "participant_name": "...",\n  "objective": "...",\n  "context": {\n    "relationship": "independent|dependent",\n    "depends_on": [],\n    "agent_parameters": {"values": {}},\n    "available_peer_results": []\n  }\n}\n```\n\n`task_name`, `task_instruction`, task graph JSON, progress events, provider traces, and final synthesis policy are not included in participant LLM prompts.\n\n## How execution can be selected without hardcoded business logic\nThe primary runtime should not decide by business keywords. The intended generic mechanism is:\n\n1. LLM extracts an abstract intent and parameters.\n2. LLM creates a minimal abstract step and required capability label.\n3. Capability registry describes available execution primitives with generic metadata: input schema, output schema, evidence level, cost, latency, permissions, network needs, and confidence.\n4. LLM/ranker chooses the best execution method by matching required capability + parameter coverage + evidence requirements.\n5. The chosen method is validated by schema and evidence checks before the result is trusted.\n\nThis keeps domain behavior in runtime-generated contracts, tool specs, registry entries, and traces rather than hardcoded ai_core branches.\n''', encoding='utf-8')
