
let state={tools:[],profiles:[],approval_policies:[]};
let selectedToolId='';
let modelSelectionState=null;
let suppressModelSettingsSave=false;
let promptDefaultState={effective:[],options:{modes:['local_only','api_only','hybrid'],providers:[],models:[]}};
let selectedPromptDefault=null;
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function api(url, options){const res=await fetch(url,options||{});const text=await res.text();let data={};try{data=text?JSON.parse(text):{};}catch(e){data={ok:false,error:text};}if(!res.ok||data.ok===false){throw new Error((data.error&&data.error.message)||data.error||data.message||('HTTP '+res.status));}return data;}
function showToast(t){const old=document.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=t;document.body.appendChild(el);setTimeout(()=>el.remove(),1800);}

function modelOptionText(item){const parts=[item.label||item.model_id||'model']; if(item.provider)parts.push(item.provider); if(item.cost_class)parts.push(item.cost_class); return parts.join(' / ');}
function fillModelSelect(select, items, value){select.innerHTML='';(items||[]).forEach(item=>{const opt=document.createElement('option');opt.value=item.model_id;opt.textContent=modelOptionText(item);opt.dataset.family=item.family||'';opt.dataset.provider=item.provider||'';if(item.requires_secret)opt.dataset.secret=item.requires_secret;select.appendChild(opt);});if(value&&Array.from(select.options).some(o=>o.value===value)){select.value=value;}else if(select.options.length){select.selectedIndex=0;}}
function settingsModelListForMode(mode, models){if(mode==='local_only')return models.local||[]; if(mode==='api_only')return models.api||[]; return models.all||[];}
function settingsDefaultModelForMode(mode, selection){if(mode==='local_only')return selection.selected_local_model_id||'qwen3.5:2b'; if(mode==='api_only')return selection.selected_api_model_id||'gpt-4o-mini'; return selection.initial_model_id||selection.selected_api_model_id||selection.selected_local_model_id||'';}
function selectedSettingsModelMeta(){const select=document.getElementById('settingsInitialModel');const opt=select.options[select.selectedIndex];return {model_id:select.value||'',family:opt?(opt.dataset.family||''):'',provider:opt?(opt.dataset.provider||''):''};}
function renderModelSettings(data){modelSelectionState=data||{};const selection=modelSelectionState.selection||{};const models=modelSelectionState.available_models||{};const mode=selection.mode||'hybrid';const profile=selection.presentation_profile||'advanced';suppressModelSettingsSave=true;document.getElementById('settingsModelMode').value=mode;document.getElementById('settingsEscalation').value=selection.allow_escalation===false?'false':'true';const profileEl=document.getElementById('settingsPresentationProfile');if(profileEl){profileEl.value=['user','advanced','developer','diagnostic'].includes(profile)?profile:'advanced';}fillModelSelect(document.getElementById('settingsInitialModel'), settingsModelListForMode(mode,models), settingsDefaultModelForMode(mode,selection));const label=document.getElementById('settingsModelLabel');if(label){label.textContent=mode==='local_only'?'Local model':(mode==='api_only'?'API model':'Initial model');}const meta=selectedSettingsModelMeta();document.getElementById('modelSettingsHint').textContent=`Mode: ${mode}; selected: ${meta.model_id||selection.initial_model_id||''}; provider: ${meta.provider||selection.initial_provider||''}; escalation: ${selection.allow_escalation===false?'disabled':'enabled'}; presentation: ${(profileEl&&profileEl.value)||profile}`;suppressModelSettingsSave=false;}
async function loadModelSettings(){try{const data=await api('/api/agent-studio/model-selection');renderModelSettings(data);}catch(e){document.getElementById('modelSettingsHint').textContent='Failed to load model settings: '+e.message;}}
async function onSettingsModelModeChanged(){if(!modelSelectionState)return;const mode=document.getElementById('settingsModelMode').value;const selection=modelSelectionState.selection||{};const models=modelSelectionState.available_models||{};fillModelSelect(document.getElementById('settingsInitialModel'), settingsModelListForMode(mode,models), settingsDefaultModelForMode(mode,selection));const label=document.getElementById('settingsModelLabel');if(label){label.textContent=mode==='local_only'?'Local model':(mode==='api_only'?'API model':'Initial model');}}
async function saveModelSettings(){if(suppressModelSettingsSave)return;const mode=document.getElementById('settingsModelMode').value;const meta=selectedSettingsModelMeta();const prev=(modelSelectionState&&modelSelectionState.selection)||{};let selectedLocal=prev.selected_local_model_id||'qwen3.5:2b';let selectedApi=prev.selected_api_model_id||'gpt-4o-mini';if(meta.family==='local'||mode==='local_only')selectedLocal=meta.model_id||selectedLocal;if(meta.family==='api'||mode==='api_only')selectedApi=meta.model_id||selectedApi;const profileEl=document.getElementById('settingsPresentationProfile');const presentationProfile=(profileEl&&profileEl.value)||prev.presentation_profile||'advanced';const payload={mode,selected_local_model_id:selectedLocal,selected_api_model_id:selectedApi,initial_model_id:meta.model_id||'',allow_escalation:document.getElementById('settingsEscalation').value!=='false',ask_for_missing_keys_at_start:true,presentation_profile:presentationProfile};if(mode==='local_only')payload.selected_local_model_id=payload.initial_model_id||selectedLocal;if(mode==='api_only')payload.selected_api_model_id=payload.initial_model_id||selectedApi;const data=await api('/api/agent-studio/model-selection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});renderModelSettings(data);showToast('Runtime settings saved');}

function promptOptionHtml(values,current){const all=[...new Set([current,...(values||[])].filter(Boolean))];return all.map(v=>`<option value="${escapeHtml(v)}" ${v===current?'selected':''}>${escapeHtml(v)}</option>`).join('');}
async function loadPromptDefaults(){const data=await api('/api/model-prompt-studio/state');promptDefaultState=data||promptDefaultState;renderPromptDefaultList();if(!selectedPromptDefault&&(promptDefaultState.effective||[]).length){selectPromptDefault((promptDefaultState.effective||[])[0].location);}}
function filteredPromptDefaults(){const f=(document.getElementById('mpFilter')?.value||'').toLowerCase();return (promptDefaultState.effective||[]).filter(x=>!f||JSON.stringify(x).toLowerCase().includes(f));}
function renderPromptDefaultList(){const list=document.getElementById('mpDefaultList');if(!list)return;const items=filteredPromptDefaults();list.innerHTML=items.map(x=>`<div class="promptItem ${selectedPromptDefault&&selectedPromptDefault.location===x.location?'active':''}" onclick='selectPromptDefault(${JSON.stringify(x.location)})'><div><b>${escapeHtml(x.location||'runtime')}</b></div><div class="small">layer=${escapeHtml(x.layer||'')} · workflow=${escapeHtml(x.workflow||'')} · graph=${escapeHtml(x.graph||'')}</div><div class="muted">mode=${escapeHtml(x.mode||'')} · provider=${escapeHtml(x.provider||'')} · model=${escapeHtml(x.model||'')}</div>${x.override?'<span class="pill">override</span>':''}</div>`).join('')||'<div class="muted">No default model/prompt entries.</div>';}
function renderPromptDefaultEditor(item){const options=promptDefaultState.options||{};document.getElementById('mpMode').innerHTML=promptOptionHtml(options.modes||['local_only','api_only','hybrid'],item.mode||'local_only');document.getElementById('mpProvider').innerHTML=promptOptionHtml(options.providers||[],item.provider||'');document.getElementById('mpModel').innerHTML=promptOptionHtml(options.models||[],item.model||'');document.getElementById('mpSystemPrompt').value=item.system_prompt||'';document.getElementById('mpUserPrompt').value=item.user_prompt||'';document.getElementById('mpSelectedMeta').textContent=`${item.layer||'runtime'} / ${item.workflow||''} / ${item.graph||''}`;}
function selectPromptDefault(location){const item=(promptDefaultState.effective||[]).find(x=>x.location===location);if(!item)return;selectedPromptDefault=item;renderPromptDefaultEditor(item);renderPromptDefaultList();}
async function savePromptDefaultOverride(){if(!selectedPromptDefault){alert('Select a layer default first.');return;}const payload={location:selectedPromptDefault.location||selectedPromptDefault.node_id,mode:document.getElementById('mpMode').value,provider:document.getElementById('mpProvider').value,model:document.getElementById('mpModel').value,system_prompt:document.getElementById('mpSystemPrompt').value,user_prompt:document.getElementById('mpUserPrompt').value,prompt_id:selectedPromptDefault.prompt_id||'',adapter_id:selectedPromptDefault.adapter_id||''};const data=await api('/api/model-prompt-studio/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});promptDefaultState.effective=data.effective||promptDefaultState.effective;promptDefaultState.options=data.options||promptDefaultState.options;selectedPromptDefault=(promptDefaultState.effective||[]).find(x=>x.location===payload.location)||selectedPromptDefault;renderPromptDefaultEditor(selectedPromptDefault);renderPromptDefaultList();showToast('Default model / prompt saved');}

async function loadSettings(){state=await api('/api/runtime/settings');renderSourceRetrievalSettings(state.source_retrieval||{});renderVerificationBrainSettings(state.verification_brain||{});renderToolList();if(selectedToolId){renderDetail(selectedToolId);}loadPromptDefaults().catch(e=>{const el=document.getElementById('mpDefaultList');if(el)el.innerHTML='<div class="muted">Failed to load model/prompt defaults: '+escapeHtml(e.message)+'</div>';});}
function renderSourceRetrievalSettings(cfg){const order=cfg.engine_order||['google','bing','duckduckgo'];const mode=cfg.routing_mode||'fallback';const threshold=cfg.verification_threshold==null?0.8:cfg.verification_threshold;const set=(id,val)=>{const el=document.getElementById(id);if(el)el.value=val;};set('sourceRoutingMode',mode);set('sourcePrimaryEngine',order[0]||'google');set('sourceSecondaryEngine',order[1]||'bing');set('sourceThirdEngine',order[2]||'duckduckgo');set('sourceVerificationThreshold',threshold);const hint=document.getElementById('sourceRetrievalHint');if(hint)hint.textContent=`Mode: ${mode}; order: ${order.join(' → ')}; threshold: ${threshold}`;}
async function saveSourceRetrievalSettings(){const order=[document.getElementById('sourcePrimaryEngine').value,document.getElementById('sourceSecondaryEngine').value,document.getElementById('sourceThirdEngine').value].filter((v,i,a)=>v&&a.indexOf(v)===i);const payload={routing_mode:document.getElementById('sourceRoutingMode').value,engine_order:order,verification_threshold:Number(document.getElementById('sourceVerificationThreshold').value||0.8),max_engines_per_request:3};const data=await api('/api/runtime/settings/source-retrieval',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});state.source_retrieval=data.source_retrieval;renderSourceRetrievalSettings(data.source_retrieval||{});showToast('Source retrieval settings saved');}

function renderVerificationBrainSettings(cfg){cfg=cfg||{};const set=(id,val)=>{const el=document.getElementById(id);if(el)el.value=String(val);};set('vbEnabled',cfg.enabled!==false);set('vbVerifyModelStages',cfg.verify_model_stages!==false);set('vbVerifyAllStages',cfg.verify_all_model_stages===true);set('vbBlockStage',cfg.block_stage_on_failure!==false);set('vbRequireMeta',cfg.require_meta_verification!==false);const setNum=(id,val,def)=>{const el=document.getElementById(id);if(el)el.value=(val==null?def:val);};setNum('vbMaxRepairRounds',cfg.max_repair_rounds,3);setNum('vbMinimumQuality',cfg.minimum_quality,0.86);setNum('vbMinimumConfidence',cfg.minimum_confidence,0.70);setNum('vbMinimumConsensus',cfg.minimum_consensus,0.70);const hint=document.getElementById('verificationBrainHint');if(hint)hint.textContent=`Enabled: ${cfg.enabled!==false}; scope: ${cfg.verify_all_model_stages?'all model stages':'main model stages'}; rounds: ${cfg.max_repair_rounds??3}; thresholds: quality ${cfg.minimum_quality??0.86}, confidence ${cfg.minimum_confidence??0.70}, consensus ${cfg.minimum_consensus??0.70}`;}
async function saveVerificationBrainSettings(){const payload={enabled:document.getElementById('vbEnabled').value==='true',verify_model_stages:document.getElementById('vbVerifyModelStages').value==='true',verify_all_model_stages:document.getElementById('vbVerifyAllStages').value==='true',block_stage_on_failure:document.getElementById('vbBlockStage').value==='true',require_meta_verification:document.getElementById('vbRequireMeta').value==='true',max_repair_rounds:Number(document.getElementById('vbMaxRepairRounds').value||3),minimum_quality:Number(document.getElementById('vbMinimumQuality').value||0.86),minimum_confidence:Number(document.getElementById('vbMinimumConfidence').value||0.70),minimum_consensus:Number(document.getElementById('vbMinimumConsensus').value||0.70)};const data=await api('/api/runtime/settings/verification-brain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});state.verification_brain=data.verification_brain;renderVerificationBrainSettings(data.verification_brain||{});showToast('Verification brain settings saved');}
function renderToolList(){const list=document.getElementById('toolList');document.getElementById('toolCount').textContent=String((state.tools||[]).length);if(!state.tools||!state.tools.length){list.innerHTML='<div class="muted">No tools registered.</div>';return;}list.innerHTML=state.tools.map(t=>{const status=t.configuration_status||{};const approval=t.approval_settings||{};return `<div class="tool ${selectedToolId===t.tool_id?'active':''}" onclick="renderDetail('${escapeHtml(t.tool_id)}')"><div class="toolName">${escapeHtml(t.name||t.tool_id)}</div><div class="small">${escapeHtml(t.tool_id)} · ${escapeHtml(t.status||'')}</div><div><span class="pill">configured: ${!!status.configured}</span><span class="pill">approval: ${escapeHtml(approval.effective_mode||approval.mode||'never')}</span></div></div>`}).join('');}
function props(schema){return (schema&&schema.properties&&typeof schema.properties==='object')?schema.properties:{};}
function getProfile(toolId){return (state.profiles||[]).find(p=>p.tool_id===toolId&&p.profile_id==='default')||{};}
function getPolicy(toolId){return (state.approval_policies||[]).find(p=>p.tool_id===toolId&&p.profile_id==='default')||{};}
function renderDetail(toolId){selectedToolId=toolId;renderToolList();const t=(state.tools||[]).find(x=>x.tool_id===toolId);if(!t){return;}document.getElementById('selectedToolTitle').textContent=toolId;const profile=getProfile(toolId);const policy=getPolicy(toolId);const conn=profile.config||{};const secretConfigured=profile.secret_configured||{};const connProps=props(t.connection_schema);const secProps=props(t.secret_schema);let html=`<div class="card"><h3 style="margin-top:0">${escapeHtml(t.name||t.tool_id)}</h3><div class="small">${escapeHtml(t.capability||'')}</div><div class="row"><span class="pill">status: ${escapeHtml(t.status||'')}</span><span class="pill">executable: ${!!t.executable}</span><span class="pill">profile: default</span></div></div>`;
html+=`<div class="card"><h3>Approval policy</h3><div class="small">Controls confirmation before external/runtime execution. Existing task UI will read this policy.</div><div class="field"><label>Mode</label><select id="approvalMode" class="select"><option value="always">Always ask: require Confirm execution every time</option><option value="once">Ask once: trust after explicit confirmation</option><option value="never">Never ask: auto-confirm this tool/profile</option></select></div><div class="row"><button class="btn ok" onclick="saveApprovalPolicy()">Save approval policy</button><span class="small">current: ${escapeHtml(policy.effective_mode||policy.mode||'never')}${policy.explicit?' · explicit':' · manifest'}${policy.trusted?' · trusted':''}</span></div></div>`;
html+=`<div class="card"><h3>Connection profile</h3><div class="small">Non-secret values are saved in the runtime connection profile. Secret fields are saved into the local runtime secret store.</div><div class="grid">`;
Object.keys(connProps).forEach(k=>{const spec=connProps[k]||{};const type=String(spec.type||'string');if(type==='boolean'){const checked=(conn[k]===true||String(conn[k]).toLowerCase()==='true'||String(conn[k])==='1')?'checked':'';html+=`<div class="field"><label>${escapeHtml(k)}</label><input id="conn_${escapeHtml(k)}" type="checkbox" ${checked} /></div>`;}else{html+=`<div class="field"><label>${escapeHtml(k)}</label><input id="conn_${escapeHtml(k)}" class="input" value="${escapeHtml(conn[k]??'')}" placeholder="${escapeHtml(k)}" /></div>`;}});
Object.keys(secProps).forEach(k=>{html+=`<div class="field"><label>${escapeHtml(k)} ${secretConfigured[k]?'(configured)':''}</label><input id="secret_${escapeHtml(k)}" type="password" class="input" value="" placeholder="leave blank to keep existing" /></div>`});
html+=`</div><div class="row"><button class="btn ok" onclick="saveProfile()">Save profile</button></div></div>`;
html+=`<div class="card"><h3>Schemas</h3><div class="pre">${escapeHtml(JSON.stringify({input_schema:t.input_schema||{},connection_schema:t.connection_schema||{},secret_schema:t.secret_schema||{},approval_policy:t.approval_policy||{},runtime_execution_policy:t.runtime_execution_policy||{}},null,2))}</div></div>`;
document.getElementById('detail').innerHTML=html;document.getElementById('approvalMode').value=(policy.effective_mode||policy.mode||'never');}
async function saveApprovalPolicy(){const mode=document.getElementById('approvalMode').value;await api('/api/runtime/settings/tool-approval',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tool_id:selectedToolId,profile_id:'default',mode})});showToast('Approval policy saved');await loadSettings();}
function typedValue(el,spec){const type=String((spec&&spec.type)||'string');if(type==='boolean')return !!el.checked;if(type==='integer'){const v=el.value;return v===''?v:parseInt(v,10);}if(type==='number'){const v=el.value;return v===''?v:Number(v);}if(type==='array'||type==='object'){try{return JSON.parse(el.value|| (type==='array'?'[]':'{}'));}catch(e){return el.value;}}return el.value;}
async function saveProfile(){const t=(state.tools||[]).find(x=>x.tool_id===selectedToolId);if(!t)return;const connProps=props(t.connection_schema);const secProps=props(t.secret_schema);const config={};const secrets={};Object.keys(connProps).forEach(k=>{const el=document.getElementById('conn_'+k);if(el)config[k]=typedValue(el,connProps[k]);});Object.keys(secProps).forEach(k=>{const el=document.getElementById('secret_'+k);if(el&&el.value)secrets[k]=el.value;});await api('/api/agent-studio/runtime-tool-profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tool_id:selectedToolId,profile_id:'default',config,secrets})});showToast('Profile saved');await loadSettings();}
loadSettings().catch(e=>{document.getElementById('toolList').innerHTML='<div class="muted">'+escapeHtml(e.message)+'</div>';});
loadModelSettings();
