from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from uuid import uuid4


class RuntimeTraceLogger:
    """Neutral trace writer with explicit runtime origin labels.

    The logger records which runtime layer produced an event without embedding
    domain-specific behavior. Event payloads are open-ended and generated by the
    caller at runtime.
    """

    def __init__(self, runtime_root: str | Path = "runtime") -> None:
        self.runtime_root = Path(runtime_root)
        self.trace_dir = self.runtime_root / "traces" / "runtime_layers"

    def record(self, *, origin: str, event_type: str, payload: dict[str, Any]) -> dict[str, Any]:
        self.trace_dir.mkdir(parents=True, exist_ok=True)
        event = {
            "trace_id": f"trace_{uuid4().hex[:12]}",
            "origin": origin,
            "event_type": event_type,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "payload": payload,
        }
        path = self.trace_dir / f"{event['trace_id']}.json"
        path.write_text(json.dumps(event, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")
        event["trace_path"] = str(path)
        return event
