from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from ai_core.config.loader import ConfigLoader
from ai_core.config.paths import RUNTIME_GENERATED, RUNTIME_KNOWLEDGE


class RuntimeTemplateGenerator:
    """
    Runtime-generated prompt/schema generator and evolver.

    Rule:
    - runtime/generated files are generated by runtime.
    - users do not manually edit runtime/generated.
    - Reject & Retry can evolve generated prompt/schema.
    - Works for known and unknown nodes.
    """

    def __init__(self) -> None:
        self.loader = ConfigLoader()
        self.prompt_dir = RUNTIME_GENERATED / "prompts"
        self.schema_dir = RUNTIME_GENERATED / "schemas"
        self.memory_dir = RUNTIME_KNOWLEDGE
        self.evolution_log = self.memory_dir / "template_evolution.jsonl"

    def ensure_node_template(self, node_id: str, executor_type: str = "llm_json") -> None:
        self.prompt_dir.mkdir(parents=True, exist_ok=True)
        self.schema_dir.mkdir(parents=True, exist_ok=True)

        prompt_path = self.prompt_dir / f"{node_id}.yaml"
        schema_path = self.schema_dir / f"{node_id}.schema.json"

        if not prompt_path.exists():
            self.loader.save_yaml(prompt_path, self._default_prompt(node_id, executor_type))

        if not schema_path.exists():
            self.loader.save_json(schema_path, self._default_schema(node_id))

    def evolve_from_feedback(
        self,
        *,
        node_id: str,
        executor_type: str = "llm_json",
        feedback: str,
        original_output: dict[str, Any] | None = None,
        user_input: str | None = None,
    ) -> dict[str, Any]:
        self.ensure_node_template(node_id, executor_type)

        prompt_path = self.prompt_dir / f"{node_id}.yaml"
        schema_path = self.schema_dir / f"{node_id}.schema.json"

        prompt = self.loader.load_yaml(prompt_path)
        schema = self.loader.load_json(schema_path)

        changes: list[str] = []
        feedback_l = (feedback or "").lower()

        # Generic structural detection: the node output had a list of strings where structured object array was requested.
        if self._needs_task_object_schema(feedback_l, original_output):
            if self._enforce_object_array_field(schema, "tasks", ["task_id", "task_type", "action", "parameters"]):
                changes.append("schema.tasks.object_array")
            if self._add_runtime_rules(prompt, [
                "tasks MUST be an array of objects, not an array of strings.",
                "Each task object MUST include task_id, task_type, action, and parameters.",
                "parameters MUST be an object containing extracted task parameters.",
            ]):
                changes.append("prompt.tasks_object_rules")

        if self._needs_human_confirmation(feedback_l):
            if self._ensure_field_in_array_items(schema, "tasks", "requires_human_confirmation", {"type": "boolean"}):
                changes.append("schema.tasks.requires_human_confirmation")
            if self._add_runtime_rules(prompt, [
                "Booking, payment, purchase, reservation, and irreversible actions MUST include requires_human_confirmation=true.",
                "Do not finalize booking/payment/purchase/reservation actions without explicit human approval.",
            ]):
                changes.append("prompt.human_confirmation_rules")

        if self._needs_more_missing_info(feedback_l):
            if self._ensure_string_array_field(schema, "missing_information"):
                changes.append("schema.missing_information.string_array")
            if self._add_runtime_rules(prompt, [
                "missing_information MUST include every required item absent from the user input.",
                "For booking/reservation tasks, missing_information should include dates, origin/destination, passenger/user details, budget/class/preferences, and final confirmation when absent.",
            ]):
                changes.append("prompt.missing_information_rules")

        # Generic extension: if feedback says "field x is required", add it to top-level schema.
        required_fields = self._extract_required_fields(feedback)
        for field in required_fields:
            if self._ensure_top_level_field(schema, field):
                changes.append(f"schema.top_level.{field}")

        if self._ensure_human_feedback_variable(prompt):
            changes.append("prompt.human_feedback_variable")

        self.loader.save_yaml(prompt_path, prompt)
        self.loader.save_json(schema_path, schema)

        event = {
            "created_at": datetime.utcnow().isoformat(),
            "node_id": node_id,
            "executor_type": executor_type,
            "feedback": feedback,
            "user_input": user_input or "",
            "changes": changes,
            "prompt_path": str(prompt_path),
            "schema_path": str(schema_path),
        }

        self.memory_dir.mkdir(parents=True, exist_ok=True)
        with self.evolution_log.open("a", encoding="utf-8") as f:
            f.write(json.dumps(event, ensure_ascii=False) + "\n")

        return event

    def _default_prompt(self, node_id: str, executor_type: str) -> dict[str, Any]:
        return {
            "id": f"{node_id}_prompt",
            "version": "1.0",
            "executor_type": executor_type,
            "system": (
                f"You are a generic runtime node executor for node '{node_id}'. "
                "Return JSON only according to the output schema. "
                "Do not execute external tools unless this node explicitly requires it."
            ),
            "user_template": (
                "User input:\n{{ user_input }}\n\n"
                "Previous results:\n{{ previous_results }}\n\n"
                "Human feedback:\n{{ human_feedback }}\n\n"
                "Correction memory:\n{{ correction_memory }}\n"
            ),
            "runtime_rules": [
                "Return one valid JSON object only.",
                "Follow the JSON schema strictly.",
                "Use human feedback and correction memory as higher-priority guidance than previous failed outputs.",
            ],
            "output_contract": self._default_contract(node_id),
        }

    def _default_contract(self, node_id: str) -> dict[str, str]:
        if node_id == "input_parsing":
            return {
                "language": "string",
                "intent_type": "string",
                "tasks": "array",
                "missing_information": "array",
                "required_capabilities": "array",
                "safety_notes": "array",
                "original_input": "string",
            }
        if node_id == "intent_recognition":
            return {
                "intent_type": "string",
                "confidence": "number",
                "tasks": "array",
                "requires_human_review": "boolean",
                "reason": "string",
            }
        if node_id == "workflow_planning":
            return {
                "planned_steps": "array",
                "blocking_missing_information": "array",
                "required_capabilities": "array",
            }
        return {"status": "string", "data": "object"}

    def _default_schema(self, node_id: str) -> dict[str, Any]:
        if node_id == "input_parsing":
            return {
                "type": "object",
                "required": ["language", "intent_type", "tasks", "missing_information", "required_capabilities", "original_input"],
                "properties": {
                    "language": {"type": "string"},
                    "intent_type": {"type": "string"},
                    "tasks": {"type": "array"},
                    "missing_information": {"type": "array", "items": {"type": "string"}},
                    "required_capabilities": {"type": "array", "items": {"type": "string"}},
                    "safety_notes": {"type": "array", "items": {"type": "string"}},
                    "original_input": {"type": "string"},
                },
                "additionalProperties": True,
            }

        if node_id == "intent_recognition":
            return {
                "type": "object",
                "required": ["intent_type", "confidence", "tasks"],
                "properties": {
                    "intent_type": {"type": "string"},
                    "confidence": {"type": "number"},
                    "tasks": {"type": "array"},
                    "requires_human_review": {"type": "boolean"},
                    "reason": {"type": "string"},
                },
                "additionalProperties": True,
            }

        if node_id == "workflow_planning":
            return {
                "type": "object",
                "required": ["planned_steps"],
                "properties": {
                    "planned_steps": {"type": "array"},
                    "blocking_missing_information": {"type": "array"},
                    "required_capabilities": {"type": "array"},
                },
                "additionalProperties": True,
            }

        return {
            "type": "object",
            "properties": {
                "status": {"type": "string"},
                "data": {"type": "object"},
            },
            "additionalProperties": True,
        }

    def _needs_task_object_schema(self, feedback: str, original_output: dict[str, Any] | None) -> bool:
        if "task_id" in feedback or "task_type" in feedback or "structured object" in feedback:
            return True
        if "string array" in feedback or "not string" in feedback:
            return True
        if "object" in feedback and "task" in feedback:
            return True
        tasks = (original_output or {}).get("tasks")
        return isinstance(tasks, list) and any(isinstance(x, str) for x in tasks)

    def _needs_human_confirmation(self, feedback: str) -> bool:
        keys = ["confirmation", "human confirmation", "booking", "payment", "purchase", "reservation", "approval"]
        return any(k in feedback for k in keys)

    def _needs_more_missing_info(self, feedback: str) -> bool:
        return "missing_information" in feedback or "missing information" in feedback or "need more" in feedback

    def _enforce_object_array_field(self, schema: dict[str, Any], field: str, required: list[str]) -> bool:
        props = schema.setdefault("properties", {})
        existing = props.get(field)
        new_schema = {
            "type": "array",
            "items": {
                "type": "object",
                "required": required,
                "properties": {
                    "task_id": {"type": "string"},
                    "task_type": {"type": "string"},
                    "action": {"type": "string"},
                    "parameters": {"type": "object"},
                    "depends_on": {"type": "array", "items": {"type": "string"}},
                    "requires_human_confirmation": {"type": "boolean"},
                },
                "additionalProperties": True,
            },
        }
        if existing == new_schema:
            return False
        props[field] = new_schema
        return True

    def _ensure_field_in_array_items(self, schema: dict[str, Any], array_field: str, field: str, field_schema: dict[str, Any]) -> bool:
        props = schema.setdefault("properties", {})
        arr = props.setdefault(array_field, {"type": "array"})
        items = arr.setdefault("items", {"type": "object"})
        item_props = items.setdefault("properties", {})
        if field not in item_props:
            item_props[field] = field_schema
            return True
        return False

    def _ensure_string_array_field(self, schema: dict[str, Any], field: str) -> bool:
        props = schema.setdefault("properties", {})
        new_schema = {"type": "array", "items": {"type": "string"}}
        if props.get(field) == new_schema:
            return False
        props[field] = new_schema
        return True

    def _ensure_top_level_field(self, schema: dict[str, Any], field: str) -> bool:
        props = schema.setdefault("properties", {})
        if field not in props:
            props[field] = {"type": ["string", "number", "boolean", "object", "array", "null"]}
            return True
        return False

    def _add_runtime_rules(self, prompt: dict[str, Any], rules_to_add: list[str]) -> bool:
        rules = prompt.setdefault("runtime_rules", [])
        changed = False
        for rule in rules_to_add:
            if rule not in rules:
                rules.append(rule)
                changed = True

        system = prompt.get("system", "")
        addition = " Use runtime_rules as mandatory constraints."
        if addition.strip() not in system:
            prompt["system"] = system + addition
            changed = True

        return changed

    def _ensure_human_feedback_variable(self, prompt: dict[str, Any]) -> bool:
        template = prompt.get("user_template", "")
        changed = False

        if "{{ human_feedback }}" not in template:
            template += "\n\nHuman feedback:\n{{ human_feedback }}\n"
            changed = True

        if "{{ correction_memory }}" not in template:
            template += "\n\nCorrection memory:\n{{ correction_memory }}\n"
            changed = True

        prompt["user_template"] = template
        return changed

    def _extract_required_fields(self, feedback: str) -> list[str]:
        # Lightweight generic parser for "need x/y/z" patterns.
        feedback_l = feedback.lower()
        if "need " not in feedback_l:
            return []

        candidates = []
        for token in feedback.replace(",", " ").replace(".", " ").split():
            clean = token.strip().strip(":;")
            if clean.isidentifier() and clean not in {"need", "needs", "required", "fields"}:
                if "_" in clean:
                    candidates.append(clean)
        return list(dict.fromkeys(candidates))
