from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from ai_core.config.loader import ConfigLoader
from ai_core.config.paths import RUNTIME_GENERATED, RUNTIME_KNOWLEDGE
from ai_core.utils.safe_json import safe_json_dumps


class RuntimeTemplateGenerator:
    """
    Runtime-generated prompt/schema generator and evolver.

    Rule:
    - runtime/generated files are generated by runtime.
    - users do not manually edit runtime/generated.
    - Reject & Retry can evolve generated prompt/schema.
    - Works for known and unknown nodes.
    """

    def __init__(self) -> None:
        self.loader = ConfigLoader()
        self.prompt_dir = RUNTIME_GENERATED / "prompts"
        self.schema_dir = RUNTIME_GENERATED / "schemas"
        self.memory_dir = RUNTIME_KNOWLEDGE
        self.evolution_log = self.memory_dir / "template_evolution.jsonl"

    def ensure_node_template(self, node_id: str, executor_type: str = "llm_json") -> None:
        self.prompt_dir.mkdir(parents=True, exist_ok=True)
        self.schema_dir.mkdir(parents=True, exist_ok=True)

        prompt_path = self.prompt_dir / f"{node_id}.yaml"
        schema_path = self.schema_dir / f"{node_id}.schema.json"

        if not prompt_path.exists():
            self.loader.save_yaml(prompt_path, self._default_prompt(node_id, executor_type))

        if not schema_path.exists():
            self.loader.save_json(schema_path, self._default_schema(node_id))

    def evolve_from_feedback(
        self,
        *,
        node_id: str,
        executor_type: str = "llm_json",
        feedback: str,
        original_output: dict[str, Any] | None = None,
        user_input: str | None = None,
    ) -> dict[str, Any]:
        self.ensure_node_template(node_id, executor_type)

        prompt_path = self.prompt_dir / f"{node_id}.yaml"
        schema_path = self.schema_dir / f"{node_id}.schema.json"

        prompt = self.loader.load_yaml(prompt_path)
        schema = self.loader.load_json(schema_path)

        changes: list[str] = []
        feedback_l = (feedback or "").lower()

        # Stage-boundary rule: input_parsing and intent_recognition must not evolve
        # toward executable tasks. Only workflow_planning owns executable steps.
        if node_id in {"input_parsing", "intent_recognition"}:
            if self._forbid_top_level_field(schema, "tasks"):
                changes.append("schema.tasks.forbidden_for_stage")
            if self._add_runtime_rules(prompt, [
                "Do not output top-level tasks in this node.",
                "Do not output executable steps, workflow, tool selection, provider selection, or implementation decisions in this node.",
                "Keep this node output limited to its stage responsibility.",
            ]):
                changes.append("prompt.stage_boundary.no_tasks")
        elif self._needs_task_object_schema(feedback_l, original_output):
            if self._add_runtime_rules(prompt, [
                "Executable work items belong in planned_steps, not top-level tasks.",
                "planned_steps MUST be an array of executable objects, not an array of strings.",
                "Each planned step object MUST include parameters and required_capability when the schema requires them.",
            ]):
                changes.append("prompt.planned_steps_object_rules")

        if self._needs_human_confirmation(feedback_l):
            if node_id in {"input_parsing", "intent_recognition"}:
                if self._add_runtime_rules(prompt, [
                    "Do not decide human confirmation for execution in this node; preserve possible safety signals only in this node's own allowed fields.",
                ]):
                    changes.append("prompt.human_confirmation.stage_boundary")
            else:
                if self._add_runtime_rules(prompt, [
                    "Any irreversible or externally mutating planned step MUST include requires_human_confirmation=true unless runtime policy explicitly allows it.",
                    "Do not finalize externally mutating actions without explicit human approval.",
                ]):
                    changes.append("prompt.human_confirmation_rules")

        if self._needs_human_review_object(feedback_l):
            if self._evolve_human_review_schema(schema):
                changes.append("schema.human_review.compatible")
            if self._add_human_review_prompt_rules(prompt):
                changes.append("prompt.human_review_rules")

        if self._needs_more_missing_info(feedback_l):
            if self._ensure_string_array_field(schema, "missing_information"):
                changes.append("schema.missing_information.string_array")
            if self._add_runtime_rules(prompt, [
                "missing_information MUST include every required item absent from the user input.",
                "For any task, missing_information should include required parameters, actor/entity details, constraints, preferences, and final confirmation when absent.",
            ]):
                changes.append("prompt.missing_information_rules")

        # Generic extension: if feedback says "field x is required", add it to top-level schema.
        required_fields = self._extract_required_fields(feedback)
        for field in required_fields:
            if self._ensure_top_level_field(schema, field):
                changes.append(f"schema.top_level.{field}")

        if self._ensure_human_feedback_variable(prompt):
            changes.append("prompt.human_feedback_variable")

        self.loader.save_yaml(prompt_path, prompt)
        self.loader.save_json(schema_path, schema)

        event = {
            "created_at": datetime.utcnow().isoformat(),
            "node_id": node_id,
            "executor_type": executor_type,
            "feedback": feedback,
            "user_input": user_input or "",
            "changes": changes,
            "prompt_path": str(prompt_path),
            "schema_path": str(schema_path),
        }

        self.memory_dir.mkdir(parents=True, exist_ok=True)
        with self.evolution_log.open("a", encoding="utf-8") as f:
            f.write(safe_json_dumps(event) + "\n")

        return event

    def _default_prompt(self, node_id: str, executor_type: str) -> dict[str, Any]:
        stage_rules = self._stage_boundary_rules(node_id)
        return {
            "id": f"{node_id}_prompt",
            "version": "2.0",
            "executor_type": executor_type,
            "system": (
                f"You are a generic runtime node executor for node '{node_id}'. "
                "Return JSON only according to the output schema. "
                "Perform only this node's stage responsibility. "
                "Do not execute external tools unless this node explicitly requires it."
            ),
            "user_template": (
                "User input:\n{{ user_input }}\n\n"
                "Runtime context:\n{{ runtime_context }}\n\n"
                "Previous results:\n{{ previous_results }}\n\n"
                "Human feedback:\n{{ human_feedback }}\n\n"
                "Correction memory:\n{{ correction_memory }}\n"
            ),
            "runtime_rules": [
                "Return one valid JSON object only.",
                "Follow the JSON schema strictly.",
                "Use human feedback and correction memory as higher-priority guidance than previous failed outputs.",
                "Keep the output minimal: include only fields needed by this node's responsibility and schema.",
                "Do not duplicate previous node outputs unless this node must reference them structurally.",
                "Do not choose a concrete tool, API provider, library, repository, or implementation unless this node is an execution/capability resolution node.",
                "Relative expressions already present in the user input are known semantic information, not missing information. Resolve them only when this node schema requires a concrete normalized value, and preserve the original expression when included.",
                "Preserve user modifiers, qualifiers, constraints, requested specificity, and completeness expectations as runtime semantics when this node is responsible for parsing or planning them.",
                "Do not rely on ai_core for business wording. Interaction wording should be generated from user input, task context, and runtime metadata.",
            ] + stage_rules,
            "output_contract": self._default_contract(node_id),
        }

    def _stage_boundary_rules(self, node_id: str) -> list[str]:
        if node_id == "input_parsing":
            return [
                "Stage responsibility: parse the user's raw input into language, original_input, parsed_entities, semantic_modifiers, constraints, temporal_expressions, missing_information, and safety_notes only.",
                "Do not generate tasks, planned_steps, workflow, required_capabilities, tool names, API names, provider names, or execution decisions.",
                "If a relative temporal expression appears, preserve it under temporal_expressions and, when runtime_context is available, include a normalized ISO value under parsed_entities without deciding execution readiness.",
                "missing_information should only contain information required to understand the input text itself; do not ask for execution details that later nodes can infer or plan.",
            ]
        if node_id == "intent_recognition":
            return [
                "Stage responsibility: classify intent from parsed input and summarize the user's request semantics only.",
                "Do not generate tasks, planned_steps, workflow, required_capabilities, tool names, API names, provider names, or execution decisions.",
                "Do not re-parse raw text when input_parsing already produced structured entities; reference or copy only minimal normalized_intent fields needed by downstream planning.",
                "confidence must be structured when the schema allows it; include overall, intent, and parameter_understanding scores.",
            ]
        if node_id == "workflow_planning":
            return [
                "Stage responsibility: convert parsed input and recognized intent into executable planned_steps.",
                "planned_steps must be executable step objects, not strings.",
                "Workflow planning may choose generic required capabilities, but must not choose concrete tools, APIs, providers, libraries, repositories, or implementation files.",
                "Each planned step should include step_id, step_type, objective, input_from, required_capability, parameters.known, parameters.optional, parameters.missing_required, execution_ready, human_interaction, next_action, depends_on, and requires_human_confirmation when allowed by the schema.",
                "Copy normalized entities from upstream nodes; do not invent stale dates or re-normalize already resolved values.",
                "Only request human_interaction when required fields are actually missing.",
            ]
        return []

    def _default_contract(self, node_id: str) -> dict[str, str]:
        if node_id == "input_parsing":
            return {
                "language": "string",
                "original_input": "string",
                "parsed_entities": "object",
                "semantic_modifiers": "array",
                "constraints": "object",
                "temporal_expressions": "array",
                "missing_information": "array",
                "safety_notes": "array",
            }
        if node_id == "intent_recognition":
            return {
                "intent_type": "string",
                "intent_summary": "string",
                "normalized_intent": "object",
                "confidence": "object",
                "human_review": "object",
            }
        if node_id == "workflow_planning":
            return {
                "planned_steps": "array",
                "blocking_missing_information": "array",
                "required_capabilities": "array",
                "human_interaction": "object optional; generate user-friendly fields only when required information is missing",
            }
        return {"status": "string", "data": "object"}

    def _default_schema(self, node_id: str) -> dict[str, Any]:
        if node_id == "input_parsing":
            return {
                "type": "object",
                "required": ["language", "original_input", "parsed_entities", "missing_information"],
                "properties": {
                    "language": {"type": "string"},
                    "original_input": {"type": "string"},
                    "parsed_entities": {"type": "object", "additionalProperties": True},
                    "semantic_modifiers": {"type": "array", "items": {"type": "string"}},
                    "constraints": {"type": "object", "additionalProperties": True},
                    "temporal_expressions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "text": {"type": "string"},
                                "normalized_value": {"type": "string"},
                                "value_type": {"type": "string"},
                            },
                            "additionalProperties": True,
                        },
                    },
                    "missing_information": {"type": "array", "items": {"type": "string"}},
                    "safety_notes": {"type": "array", "items": {"type": "string"}},
                },
                "not": {"required": ["tasks"]},
                "additionalProperties": True,
            }

        if node_id == "intent_recognition":
            return {
                "type": "object",
                "required": ["intent_type", "confidence"],
                "properties": {
                    "intent_type": {"type": "string"},
                    "intent_summary": {"type": "string"},
                    "normalized_intent": {"type": "object", "additionalProperties": True},
                    "confidence": {
                        "oneOf": [
                            {"type": "number"},
                            {
                                "type": "object",
                                "properties": {
                                    "overall": {"type": "number"},
                                    "intent": {"type": "number"},
                                    "parameter_understanding": {"type": "number"},
                                    "execution_readiness": {"type": "number"},
                                },
                                "additionalProperties": True,
                            },
                        ]
                    },
                    "human_review": {"type": "object", "additionalProperties": True},
                    "reason": {"type": "string"},
                },
                "not": {"required": ["tasks"]},
                "additionalProperties": True,
            }

        if node_id == "workflow_planning":
            return {
                "type": "object",
                "required": ["planned_steps"],
                "properties": {
                    "planned_steps": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "step_id", "step_type", "objective", "input_from",
                                "parameters", "required_capability", "execution_ready",
                                "human_interaction", "next_action"
                            ],
                            "properties": {
                                "step_id": {"type": "string"},
                                "step_type": {"type": "string"},
                                "task_id": {"type": "string"},
                                "task_type": {"type": "string"},
                                "action": {"type": "string"},
                                "objective": {"type": "string"},
                                "input_from": {"type": "array", "items": {"type": "string"}},
                                "parameters": {
                                    "type": "object",
                                    "properties": {
                                        "known": {"type": "object", "additionalProperties": True},
                                        "optional": {"type": "object", "additionalProperties": True},
                                        "missing_required": {"oneOf": [{"type": "object"}, {"type": "array"}]}
                                    },
                                    "additionalProperties": True,
                                },
                                "required_capability": {"oneOf": [{"type": "string"}, {"type": "object"}]},
                                "execution_ready": {"type": "boolean"},
                                "human_interaction": {"type": "object", "additionalProperties": True},
                                "next_action": {"type": "string"},
                                "depends_on": {"type": "array"},
                                "requires_human_confirmation": {"type": "boolean"},
                                "missing_fields": {"type": "array"},
                            },
                            "additionalProperties": True,
                        },
                    },
                    "blocking_missing_information": {"oneOf": [{"type": "array"}, {"type": "object"}]},
                    "required_capabilities": {"type": "array"},
                    "human_interaction": {"type": "object"},
                },
                "additionalProperties": True,
            }

        return {
            "type": "object",
            "properties": {
                "status": {"type": "string"},
                "data": {"type": "object"},
            },
            "additionalProperties": True,
        }

    def _needs_task_object_schema(self, feedback: str, original_output: dict[str, Any] | None) -> bool:
        if "task_id" in feedback or "task_type" in feedback or "structured object" in feedback:
            return True
        if "string array" in feedback or "not string" in feedback:
            return True
        if "object" in feedback and "task" in feedback:
            return True
        tasks = (original_output or {}).get("tasks")
        return isinstance(tasks, list) and any(isinstance(x, str) for x in tasks)

    def _needs_human_confirmation(self, feedback: str) -> bool:
        keys = [
            "confirmation",
            "human confirmation",
            "approval",
            "irreversible",
            "external action",
            "mutating action",
            "side effect",
        ]
        return any(k in feedback for k in keys)

    def _needs_more_missing_info(self, feedback: str) -> bool:
        return "missing_information" in feedback or "missing information" in feedback or "need more" in feedback

    def _enforce_object_array_field(self, schema: dict[str, Any], field: str, required: list[str]) -> bool:
        props = schema.setdefault("properties", {})
        existing = props.get(field)
        new_schema = {
            "type": "array",
            "items": {
                "type": "object",
                "required": required,
                "properties": {
                    "task_id": {"type": "string"},
                    "task_type": {"type": "string"},
                    "action": {"type": "string"},
                    "parameters": {"type": "object"},
                    "depends_on": {"type": "array", "items": {"type": "string"}},
                    "requires_human_confirmation": {"type": "boolean"},
                },
                "additionalProperties": True,
            },
        }
        if existing == new_schema:
            return False
        props[field] = new_schema
        return True

    def _forbid_top_level_field(self, schema: dict[str, Any], field: str) -> bool:
        changed = False
        props = schema.setdefault("properties", {})
        if field in props:
            props.pop(field, None)
            changed = True
        required = schema.get("required")
        if isinstance(required, list) and field in required:
            schema["required"] = [x for x in required if x != field]
            changed = True
        if schema.get("not") != {"required": [field]}:
            schema["not"] = {"required": [field]}
            changed = True
        return changed

    def _ensure_field_in_array_items(self, schema: dict[str, Any], array_field: str, field: str, field_schema: dict[str, Any]) -> bool:
        props = schema.setdefault("properties", {})
        arr = props.setdefault(array_field, {"type": "array"})
        items = arr.setdefault("items", {"type": "object"})
        item_props = items.setdefault("properties", {})
        if field not in item_props:
            item_props[field] = field_schema
            return True
        return False

    def _ensure_string_array_field(self, schema: dict[str, Any], field: str) -> bool:
        props = schema.setdefault("properties", {})
        new_schema = {"type": "array", "items": {"type": "string"}}
        if props.get(field) == new_schema:
            return False
        props[field] = new_schema
        return True

    def _ensure_top_level_field(self, schema: dict[str, Any], field: str) -> bool:
        props = schema.setdefault("properties", {})
        if field not in props:
            props[field] = {"type": ["string", "number", "boolean", "object", "array", "null"]}
            return True
        return False

    def _add_runtime_rules(self, prompt: dict[str, Any], rules_to_add: list[str]) -> bool:
        rules = prompt.setdefault("runtime_rules", [])
        changed = False
        for rule in rules_to_add:
            if rule not in rules:
                rules.append(rule)
                changed = True

        system = prompt.get("system", "")
        addition = " Use runtime_rules as mandatory constraints."
        if addition.strip() not in system:
            prompt["system"] = system + addition
            changed = True

        return changed

    def _ensure_human_feedback_variable(self, prompt: dict[str, Any]) -> bool:
        template = prompt.get("user_template", "")
        changed = False

        if "{{ human_feedback }}" not in template:
            template += "\n\nHuman feedback:\n{{ human_feedback }}\n"
            changed = True

        if "{{ correction_memory }}" not in template:
            template += "\n\nCorrection memory:\n{{ correction_memory }}\n"
            changed = True

        prompt["user_template"] = template
        return changed


    def _needs_human_review_object(self, feedback: str) -> bool:
        return (
            "human_review object" in feedback
            or ("requires_human_review" in feedback and "object" in feedback)
            or ("not of type 'boolean'" in feedback and "requires_human_review" in feedback)
            or ("is not of type" in feedback and "requires_human_review" in feedback)
        )

    def _evolve_human_review_schema(self, schema: dict[str, Any]) -> bool:
        props = schema.setdefault("properties", {})
        changed = False
        compatible = {
            "anyOf": [
                {"type": "boolean"},
                {
                    "type": "object",
                    "properties": {
                        "status": {"type": "string"},
                        "required": {"type": "boolean"},
                        "reason": {"type": "string"},
                        "reasons": {"type": "array", "items": {"type": "string"}},
                        "review_stage": {"type": "string"},
                    },
                    "additionalProperties": True,
                },
            ]
        }
        if props.get("requires_human_review") != compatible:
            props["requires_human_review"] = compatible
            changed = True
        human_review_schema = {
            "type": "object",
            "properties": {
                "required": {"type": "boolean"},
                "review_stage": {"type": "string"},
                "reasons": {"type": "array", "items": {"type": "string"}},
            },
            "additionalProperties": True,
        }
        if props.get("human_review") != human_review_schema:
            props["human_review"] = human_review_schema
            changed = True
        return changed

    def _add_human_review_prompt_rules(self, prompt: dict[str, Any]) -> bool:
        return self._add_runtime_rules(prompt, [
            "If the schema allows human_review, prefer human_review.required, human_review.review_stage, and human_review.reasons.",
            "If requires_human_review is present and schema expects boolean, use true or false only.",
            "Do not output an object into a boolean-only field unless schema explicitly allows it.",
        ])

    def _extract_required_fields(self, feedback: str) -> list[str]:
        # Lightweight generic parser for "need x/y/z" patterns.
        feedback_l = feedback.lower()
        if "need " not in feedback_l:
            return []

        candidates = []
        for token in feedback.replace(",", " ").replace(".", " ").split():
            clean = token.strip().strip(":;")
            if clean.isidentifier() and clean not in {"need", "needs", "required", "fields"}:
                if "_" in clean:
                    candidates.append(clean)
        return list(dict.fromkeys(candidates))
