from __future__ import annotations

import json
import re
from datetime import datetime
from typing import Any

from ai_core.config.paths import RUNTIME_GENERATED


class InteractionContractGenerator:
    """Build frontend interaction contracts from runtime-generated metadata.

    v40 rule:
    - ai_core must not contain business/domain field dictionaries.
    - ai_core must not infer field meaning from business keywords.
    - ai_core only normalizes and transports fields already produced by the
      runtime intelligence layer.
    - If user-friendly labels/questions/placeholders/options are required,
      they must be generated by LLM/runtime metadata before reaching this class.
    - The fallback in this class is intentionally generic and domain-neutral.
    """

    def __init__(self) -> None:
        self.request_dir = RUNTIME_GENERATED / "interaction_generation_requests"

    def build_request(
        self,
        interactions: list[dict[str, Any]],
        *,
        user_input: str = "",
        language: str | None = None,
    ) -> dict[str, Any]:
        fields: list[dict[str, Any]] = []
        seen: set[tuple[str, str]] = set()
        title = "Additional information required"
        message = "Please provide the missing information below so the workflow can continue."
        submit_label = "Save information & continue"
        cancel_label = "Cancel workflow"

        for interaction in interactions or []:
            step_id = str(interaction.get("step_id", ""))
            source_step = interaction.get("source_step") if isinstance(interaction.get("source_step"), dict) else {}
            original_required_fields = self._collect_raw_fields(interaction, source_step)

            runtime_contract = self._runtime_contract_from_interaction(interaction, source_step)
            if runtime_contract:
                title = self._text_or(runtime_contract.get("title"), title)
                message = self._text_or(runtime_contract.get("message"), message)
                submit_label = self._text_or(runtime_contract.get("submit_label"), submit_label)
                cancel_label = self._text_or(runtime_contract.get("cancel_label"), cancel_label)
                raw_fields = runtime_contract.get("fields", []) or []
            else:
                raw_fields = original_required_fields

            for index, raw_field in enumerate(raw_fields):
                field = self._normalize_field(raw_field, step_id=step_id, source_step=source_step)
                self._attach_merge_metadata(field, raw_field, original_required_fields, index=index, step_id=step_id)
                key = (field.get("step_id", ""), field.get("field", ""))
                if key[1] and key not in seen:
                    seen.add(key)
                    fields.append(field)

        generation_request = self._write_generation_request(
            interactions=interactions,
            fields=fields,
            user_input=user_input,
            language=language,
        )

        return {
            "kind": "human_information_required",
            "type": "form",
            "status": "waiting_for_user_input",
            "title": title,
            "message": message,
            "fields": fields,
            "submit_label": submit_label,
            "cancel_label": cancel_label,
            "expected_response_format": {"answers": {"<field name>": "<value>"}},
            "field_mapping": self._field_mapping(fields),
            "resume_strategy": {"type": "resume_workflow", "merge_target": "workflow_planning"},
            "runtime_generation": generation_request,
        }

    def _runtime_contract_from_interaction(self, interaction: dict[str, Any], source_step: dict[str, Any]) -> dict[str, Any] | None:
        """Return a runtime/LLM-generated interaction contract when available.

        The keys below are generic metadata slots, not business concepts.
        """
        for source in [interaction, source_step]:
            if not isinstance(source, dict):
                continue
            for key in ["human_interaction", "interaction", "interaction_contract", "runtime_interaction"]:
                candidate = source.get(key)
                if isinstance(candidate, dict) and isinstance(candidate.get("fields"), list) and candidate.get("fields"):
                    return candidate
        return None

    def _collect_raw_fields(self, interaction: dict[str, Any], source_step: dict[str, Any]) -> list[Any]:
        """Collect raw required-field metadata without interpreting meaning."""
        raw_fields: list[Any] = []

        for value in [interaction.get("fields"), interaction.get("missing_fields"), source_step.get("missing_fields")]:
            if isinstance(value, list):
                raw_fields.extend(value)

        params = source_step.get("parameters") if isinstance(source_step, dict) else None
        if isinstance(params, dict):
            missing_required = params.get("missing_required")
            if isinstance(missing_required, dict):
                raw_fields.extend([key for key, value in missing_required.items() if value in [None, "", [], {}]])
            elif isinstance(missing_required, list):
                raw_fields.extend(missing_required)

        return list(self._dedupe_raw_fields(raw_fields))

    def _dedupe_raw_fields(self, fields: list[Any]):
        seen: set[str] = set()
        for field in fields:
            key = self._field_name(field)
            if key and key not in seen:
                seen.add(key)
                yield field

    def _normalize_field(self, raw_field: Any, *, step_id: str, source_step: dict[str, Any]) -> dict[str, Any]:
        """Normalize field metadata without domain-specific inference.

        If runtime/LLM provides label/question/type/options/examples, preserve them.
        If not, produce a generic but usable field so the UI can ask the user.
        """
        if isinstance(raw_field, dict):
            field_name = self._field_name(raw_field)
            field = {
                "step_id": str(raw_field.get("step_id") or step_id),
                "field": self._safe_field_id(field_name),
                "source_field": field_name,
                "label": self._first_text(raw_field, ["label", "title", "display_name"]) or self._generic_label(field_name),
                "question": self._first_text(raw_field, ["question", "prompt", "message"]) or self._generic_question(field_name),
                "type": self._first_text(raw_field, ["type", "input_type", "ui_type"]) or "text",
                "required": bool(raw_field.get("required", True)),
            }

            options = raw_field.get("options") or raw_field.get("choices") or raw_field.get("enum")
            if isinstance(options, list) and options:
                field["options"] = [str(x) for x in options]
                if field["type"] in {"text", "string"}:
                    field["type"] = "select"

            for key in ["placeholder", "description", "examples", "help_text"]:
                if raw_field.get(key):
                    field[key] = raw_field[key]

            field.setdefault("placeholder", self._generic_placeholder(field_name))
            field.setdefault("description", self._generic_description(source_step))
            return field

        field_name = str(raw_field).strip()
        return {
            "step_id": step_id,
            "field": self._safe_field_id(field_name),
            "source_field": field_name,
            "label": self._generic_label(field_name),
            "question": self._generic_question(field_name),
            "type": "text",
            "required": True,
            "placeholder": self._generic_placeholder(field_name),
            "description": self._generic_description(source_step),
        }


    def _attach_merge_metadata(
        self,
        field: dict[str, Any],
        raw_field: Any,
        original_required_fields: list[Any],
        *,
        index: int,
        step_id: str,
    ) -> None:
        """Attach generic merge metadata for resume.

        This method does not infer business meaning. It only preserves aliases
        that already exist in runtime metadata and, when a runtime/LLM contract
        rewrites the visible field name, keeps the original required field by
        position so the submitted answer can be merged back safely.
        """
        aliases: list[str] = []

        for value in [
            field.get("field"),
            field.get("source_field"),
            self._field_name(raw_field),
        ]:
            if isinstance(value, str) and value.strip():
                aliases.append(value.strip())

        if isinstance(raw_field, dict):
            for key in ["source_field", "original_field", "merge_field", "parameter", "parameter_name"]:
                value = raw_field.get(key)
                if isinstance(value, str) and value.strip():
                    aliases.append(value.strip())
            raw_aliases = raw_field.get("aliases") or raw_field.get("merge_aliases")
            if isinstance(raw_aliases, list):
                aliases.extend(str(x).strip() for x in raw_aliases if str(x).strip())

        if index < len(original_required_fields):
            original = self._field_name(original_required_fields[index])
            if original:
                aliases.append(original)
                field.setdefault("source_field", original)

        unique_aliases = self._unique_texts(aliases)
        field["aliases"] = unique_aliases
        field["merge_targets"] = [
            {"step_id": step_id, "source_field": alias}
            for alias in unique_aliases
        ]

    def _field_mapping(self, fields: list[dict[str, Any]]) -> dict[str, Any]:
        mapping: dict[str, Any] = {}
        for field in fields:
            field_id = str(field.get("field") or "").strip()
            if not field_id:
                continue
            mapping[field_id] = {
                "step_id": str(field.get("step_id") or ""),
                "source_field": str(field.get("source_field") or ""),
                "aliases": list(field.get("aliases") or []),
                "merge_targets": list(field.get("merge_targets") or []),
            }
        return mapping

    def _unique_texts(self, values: list[str]) -> list[str]:
        seen: set[str] = set()
        result: list[str] = []
        for value in values:
            text = str(value or "").strip()
            if not text:
                continue
            key = self._safe_field_id(text)
            if key and key not in seen:
                seen.add(key)
                result.append(text)
        return result

    def _field_name(self, raw_field: Any) -> str:
        if isinstance(raw_field, dict):
            return self._first_text(raw_field, ["field", "field_id", "name", "id", "key", "parameter", "parameter_name"])
        return str(raw_field or "").strip()

    def _first_text(self, data: dict[str, Any], keys: list[str]) -> str:
        for key in keys:
            value = data.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
        return ""

    def _text_or(self, value: Any, fallback: str) -> str:
        return value.strip() if isinstance(value, str) and value.strip() else fallback

    def _safe_field_id(self, field_name: str) -> str:
        value = str(field_name or "").strip().lower()
        value = re.sub(r"[^a-z0-9A-Z]+", "_", value).strip("_")
        return value or "required_value"

    def _generic_label(self, field_name: str) -> str:
        normalized = str(field_name or "").replace("_", " ").replace("-", " ").strip()
        normalized = re.sub(r"\s+", " ", normalized)
        return normalized or "Required information"

    def _generic_question(self, field_name: str) -> str:
        label = self._generic_label(field_name)
        return f"Please provide this information: {label}."

    def _generic_placeholder(self, field_name: str) -> str:
        label = self._generic_label(field_name)
        return f"Enter {label}"

    def _generic_description(self, source_step: dict[str, Any]) -> str:
        objective = source_step.get("objective") or source_step.get("description") or source_step.get("action")
        if isinstance(objective, str) and objective.strip():
            return f"This information is required to continue this step: {objective.strip()}."
        return "This information is required to continue the workflow."

    def _write_generation_request(
        self,
        *,
        interactions: list[dict[str, Any]],
        fields: list[dict[str, Any]],
        user_input: str,
        language: str | None,
    ) -> dict[str, Any]:
        self.request_dir.mkdir(parents=True, exist_ok=True)
        request_id = "interaction_" + datetime.utcnow().strftime("%Y%m%d%H%M%S%f")
        request_path = self.request_dir / f"{request_id}.json"
        request = {
            "request_id": request_id,
            "created_at": datetime.utcnow().isoformat(),
            "status": "pending_runtime_or_llm_naturalization",
            "purpose": "Generate user-friendly interaction wording from runtime missing-field metadata.",
            "core_rule": "Do not place business/domain dictionaries or keyword inference in ai_core. All domain wording, examples, input types, and options must come from runtime metadata or LLM generation.",
            "language": language or "auto",
            "user_input": user_input,
            "input_interactions": interactions,
            "generic_fallback_fields": fields,
            "expected_output_schema": {
                "type": "object",
                "properties": {
                    "title": {"type": "string"},
                    "message": {"type": "string"},
                    "fields": {"type": "array"},
                },
                "required": ["fields"],
                "additionalProperties": True,
            },
        }
        request_path.write_text(json.dumps(request, ensure_ascii=False, indent=2), encoding="utf-8")
        return {"request_id": request_id, "request_path": str(request_path)}
