from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class PresentationRequest:
    """Generic request for final user-facing presentation.

    Presentation Brain must not execute tools, search, repair, or create facts.
    It only assembles already-produced runtime material into a delivery-ready
    response.
    """

    run_id: str
    node_id: str
    original_input: str = ""
    state: dict[str, Any] = field(default_factory=dict)
    materials: list[dict[str, Any]] = field(default_factory=list)
    trust_summary: dict[str, Any] = field(default_factory=dict)
    output_policy: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class PresentationResult:
    """Structured output generated by Presentation Brain."""

    status: str
    final_answer: str
    message: str
    result_material: list[dict[str, Any]] = field(default_factory=list)
    synthesis: dict[str, Any] = field(default_factory=dict)
    delivery_format: str = "text"
    source: str = "presentation_brain"

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "final_answer": self.final_answer,
            "message": self.message,
            "result_material": self.result_material,
            "synthesis": self.synthesis,
            "delivery_format": self.delivery_format,
            "source": self.source,
        }
