from __future__ import annotations

from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[2]
AI_CORE_DIR = ROOT_DIR / "ai_core"
CONFIGS_DIR = ROOT_DIR / "configs"
SCHEMA_DIR = ROOT_DIR / "schema"
RUNTIME_DIR = ROOT_DIR / "runtime"
RUNTIME_CONFIGS_DIR = RUNTIME_DIR / "configs"
RUNTIME_PROMPTS_DIR = RUNTIME_CONFIGS_DIR / "prompts"
RUNTIME_WORKFLOWS_DIR = RUNTIME_CONFIGS_DIR / "workflows"
RUNTIME_INTENTS_DIR = RUNTIME_CONFIGS_DIR / "intents"
RUNTIME_MODELS_DIR = RUNTIME_CONFIGS_DIR / "models"
RUNTIME_TOOLS_DIR = RUNTIME_CONFIGS_DIR / "tools"
RUNTIME_CAPABILITIES_DIR = RUNTIME_CONFIGS_DIR / "capabilities"
RUNTIME_KNOWLEDGE_DIR = RUNTIME_DIR / "knowledge"
RUNTIME_MEMORY_DIR = RUNTIME_DIR / "memory"
RUNTIME_TRACES_DIR = RUNTIME_DIR / "traces"
RUNTIME_DATASETS_DIR = RUNTIME_DIR / "datasets"
RUNTIME_SECRETS_DIR = RUNTIME_DIR / "secrets"
RUNTIME_LOGS_DIR = RUNTIME_DIR / "logs"
