from __future__ import annotations

from typing import Any


def default_command_set() -> dict[str, Any]:
    """Return the built-in Studio command registry.

    The registry maps command expressions to generic Studio actions.  It is not
    business/domain logic: commands describe management operations such as
    creating participants, tasks, artifact lifecycle, runtime input, workflow
    control, and command-set customization.  Runtime customizations are merged
    from runtime/configs and can add, disable, or override commands without
    editing source code.
    """
    commands: list[dict[str, Any]] = [
        {
            "command_id": "create_participant",
            "category": "agent",
            "action": "create_participant",
            "enabled": True,
            "priority": 100,
            "patterns": ["create an agent", "create agent", "create a participant", "create participant", "add an agent"],
            "description": "Create a reusable participant/agent profile.",
        },
        {
            "command_id": "update_participant",
            "category": "agent",
            "action": "update_participant",
            "enabled": True,
            "priority": 90,
            "patterns": ["update agent", "modify agent", "change agent", "rename agent"],
            "description": "Update a participant/agent definition.",
        },
        {
            "command_id": "delete_participant",
            "category": "agent",
            "action": "delete_participant",
            "enabled": True,
            "priority": 90,
            "patterns": ["delete agent", "remove agent", "disable agent"],
            "description": "Remove or disable a participant/agent.",
        },
        {
            "command_id": "list_participants",
            "category": "agent",
            "action": "list_participants",
            "enabled": True,
            "priority": 80,
            "patterns": ["list agents", "show agents", "list participants", "show participants"],
            "description": "List known participants/agents.",
        },
        {
            "command_id": "create_task",
            "category": "task",
            "action": "create_task",
            "enabled": True,
            "priority": 100,
            "patterns": ["create a task", "create task", "add task", "define task"],
            "description": "Create a task/workflow graph.",
        },
        {
            "command_id": "execute_task",
            "category": "task",
            "action": "execute_task",
            "enabled": True,
            "priority": 100,
            "patterns": ["start task", "run task", "execute task", "execute", "run"],
            "description": "Execute a task/workflow graph.",
        },
        {
            "command_id": "pause_task",
            "category": "task",
            "action": "pause_task",
            "enabled": True,
            "priority": 70,
            "patterns": ["pause task", "suspend task"],
            "description": "Pause a running or pending task.",
        },
        {
            "command_id": "resume_task",
            "category": "task",
            "action": "resume_task",
            "enabled": True,
            "priority": 70,
            "patterns": ["resume task", "continue task", "continue workflow", "resume workflow"],
            "description": "Resume a suspended task/workflow.",
        },
        {
            "command_id": "cancel_task",
            "category": "task",
            "action": "cancel_task",
            "enabled": True,
            "priority": 70,
            "patterns": ["cancel task", "stop task", "abort task"],
            "description": "Cancel a task/workflow run.",
        },
        {
            "command_id": "show_workflow",
            "category": "workflow",
            "action": "show_workflow",
            "enabled": True,
            "priority": 70,
            "patterns": ["show workflow", "show graph", "show steps", "show workflow graph"],
            "description": "Show workflow details.",
        },
        {
            "command_id": "approve_workflow",
            "category": "workflow",
            "action": "approve_workflow",
            "enabled": True,
            "priority": 75,
            "patterns": ["approve workflow", "approve step", "confirm workflow"],
            "description": "Approve a workflow or step.",
        },
        {
            "command_id": "reject_workflow",
            "category": "workflow",
            "action": "reject_workflow",
            "enabled": True,
            "priority": 75,
            "patterns": ["reject workflow", "reject step", "revise workflow"],
            "description": "Reject or revise a workflow or step.",
        },
        {
            "command_id": "upload_artifact",
            "category": "artifact",
            "action": "upload_artifact",
            "enabled": True,
            "priority": 80,
            "patterns": ["upload artifact", "upload file", "add file", "attach file"],
            "description": "Upload or attach an artifact.",
        },
        {
            "command_id": "artifact_edit",
            "category": "artifact",
            "action": "artifact_edit",
            "enabled": True,
            "priority": 110,
            "patterns": ["edit uploaded file", "modify uploaded file", "change the file", "modify the file", "update the file", "generate a new code file", "generate a new file"],
            "description": "Create a reviewable modification proposal for an uploaded artifact.",
        },
        {
            "command_id": "artifact_review_confirm",
            "category": "artifact",
            "action": "artifact_review_confirm",
            "enabled": True,
            "priority": 90,
            "patterns": ["confirm artifact", "confirm replacement", "apply artifact edit", "apply file edit"],
            "description": "Confirm artifact replacement after review.",
        },
        {
            "command_id": "artifact_review_cancel",
            "category": "artifact",
            "action": "artifact_review_cancel",
            "enabled": True,
            "priority": 90,
            "patterns": ["cancel artifact edit", "discard artifact edit", "cancel file edit"],
            "description": "Cancel an artifact edit proposal.",
        },
        {
            "command_id": "download_artifact",
            "category": "artifact",
            "action": "download_artifact",
            "enabled": True,
            "priority": 80,
            "patterns": ["download artifact", "download file"],
            "description": "Download an artifact or draft.",
        },
        {
            "command_id": "submit_runtime_input",
            "category": "runtime_input",
            "action": "submit_runtime_input",
            "enabled": True,
            "priority": 80,
            "patterns": ["provide input", "submit parameters", "submit runtime input", "continue with"],
            "description": "Submit runtime input required by a suspended workflow.",
        },

        {
            "command_id": "create_runtime_service",
            "category": "runtime_service",
            "action": "create_runtime_service",
            "enabled": True,
            "priority": 95,
            "patterns": ["create runtime service", "create a runtime service", "add runtime service", "define runtime service"],
            "description": "Create a runtime-managed background service definition.",
        },
        {
            "command_id": "start_runtime_service",
            "category": "runtime_service",
            "action": "start_runtime_service",
            "enabled": True,
            "priority": 95,
            "patterns": ["start runtime service", "enable runtime service", "run runtime service"],
            "description": "Start a runtime-managed background service.",
        },
        {
            "command_id": "stop_runtime_service",
            "category": "runtime_service",
            "action": "stop_runtime_service",
            "enabled": True,
            "priority": 90,
            "patterns": ["stop runtime service", "disable runtime service", "pause runtime service"],
            "description": "Stop a runtime-managed background service.",
        },
        {
            "command_id": "list_runtime_services",
            "category": "runtime_service",
            "action": "list_runtime_services",
            "enabled": True,
            "priority": 85,
            "patterns": ["list runtime services", "show runtime services", "runtime service status", "show services"],
            "description": "List runtime-managed background services.",
        },
        {
            "command_id": "create_tool",
            "category": "tool",
            "action": "create_tool",
            "enabled": True,
            "priority": 70,
            "patterns": ["create tool", "generate tool", "make tool"],
            "description": "Create or generate a runtime tool.",
        },
        {
            "command_id": "test_tool",
            "category": "tool",
            "action": "test_tool",
            "enabled": True,
            "priority": 70,
            "patterns": ["test tool", "verify tool", "sandbox tool"],
            "description": "Test a tool in a sandbox or validation flow.",
        },
        {
            "command_id": "list_models",
            "category": "model_provider",
            "action": "list_models",
            "enabled": True,
            "priority": 60,
            "patterns": ["list models", "show models", "show provider status", "list providers"],
            "description": "Show model/provider status.",
        },
        {
            "command_id": "set_provider",
            "category": "model_provider",
            "action": "set_provider",
            "enabled": True,
            "priority": 60,
            "patterns": ["set provider", "switch model", "change model", "enable fallback"],
            "description": "Change model/provider routing settings.",
        },
        {
            "command_id": "show_trace",
            "category": "execution",
            "action": "show_trace",
            "enabled": True,
            "priority": 60,
            "patterns": ["show trace", "show evidence", "show logs", "verify execution"],
            "description": "Show execution trace or evidence.",
        },
        {
            "command_id": "feedback_adaptation",
            "category": "feedback",
            "action": "feedback_adaptation",
            "enabled": True,
            "priority": 95,
            "patterns": ["upgrade model", "upgrading the model", "stronger model", "re-optimize", "reoptimized", "re-optimized", "optimize again", "too complex", "not satisfied", "not good", "wrong result", "result is wrong", "rerun with", "try again"],
            "description": "Record feedback and trigger runtime adaptation or re-optimization.",
        },
        {
            "command_id": "list_command_set",
            "category": "command_set",
            "action": "list_command_set",
            "enabled": True,
            "priority": 120,
            "patterns": ["list command set", "show command set", "show commands", "list commands", "列出指令集", "显示指令集"],
            "description": "List the effective command registry.",
        },
        {
            "command_id": "update_command_set",
            "category": "command_set",
            "action": "update_command_set",
            "enabled": True,
            "priority": 120,
            "patterns": ["update command set", "modify command set", "change command set", "customize command set", "add phrase", "remove phrase", "add command", "remove command", "修改指令集", "更新指令集", "自定义指令集"],
            "description": "Modify the runtime command registry.",
        },
    ]
    return {
        "version": "2.0",
        "scope": "agent_studio_default_command_registry",
        "description": "Default command registry for Studio management operations.",
        "commands": commands,
        "feedback_intents": {
            "upgrade_quality": ["upgrade model", "upgrading the model", "stronger model", "higher quality model", "better model"],
            "retry_or_reoptimize": ["re-optimize", "reoptimized", "re-optimized", "optimize again", "rerun", "try again"],
            "dissatisfaction": ["not satisfied", "not good", "wrong result", "result is wrong", "too complex", "too messy", "needs to be improved"],
        },
    }
